name: 'Get pull request creator informations'
description: ''
author: 'Benedict'
inputs:
  JIRA_ISSUE_API_URL:
    required: true
    description: "jira api"
  BRANCH_NAME:
    required: false
    description: "branch name with jira issue key"
  GITHUB_TOKEN:
    required: true
    description: "github action for authentication"
  FETCH_ON_MERGE_PR:
    required: false
    description: "fetch issue on merging pr to another branch"
    default: "fetch issue on push"
runs:
  using: 'node16'
  main: 'dist/index.js'
