name: 'build-test'
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          yarn
      - run: |
          yarn run all
  test: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        id: retrieve_jira_issue
        with:
          JIRA_ISSUE_API_URL: ${{secrets.JIRA_ISSUE_API_URL}}
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          FETCH_ON_MERGE_PR: true
          JIRA_AUTH_TOKEN: ${{ secrets.JIRA_AUTH }}
      - name: Get jira issues
        run: |
          echo `raw output ${{ steps.retrieve_jira_issue.outputs.rawIssues }}`
