name: 'build-test'
on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          yarn
      - run: |
          yarn run all
  test: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: retrieve_jira_issue
        with:
          JIRA_ISSUE_API_URL: ${{secrets.JIRA_ISSUE_API_URL}}
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          BRANCH_NAME: feat/TO-169-branch-name-TO-168
          JIRA_AUTH_TOKEN: ${{ secrets.JIRA_AUTH }}
          FETCH_ON_MERGE_PR: false
      - name: Get jira issues
        run: |
          echo "raw output ${{ steps.retrieve_jira_issue.outputs.rawIssues }}"
          echo "Stringfied output ${{ steps.retrieve_jira_issue.outputs.stringfiedIssues }}"
